name: revali_core
version: 1.4.0
description: Classes to share between Revali and Revali Annotations
repository: https://github.com/mrgnhnt96/revali/tree/main/packages/revali_core
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
    - https://github.com/sponsors/mrgnhnt96
topics:
  - revali
  - api
  - backend
  - server
  - code-generation

environment:
  sdk: '>=3.2.6 <4.0.0'
dev_dependencies:
  test: ^1.25.15
