targets:
  $default:
    sources:
      exclude:
        - test/fixtures/**
    builders:
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**
        options:
          explicit_to_json: true
          include_if_null: true
          any_map: true
          field_rename: snake