name: hello
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    revali_router:
        path: ../../revali_router/revali_router

dev_dependencies:
    revali:
        path: ../../packages/revali
    revali_server:
        path: ../../constructs/revali_server
    