import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    // tutorialSidebar: [
    //     {
    //         type: 'category', // This specifies that this is a category. Categories can contain sub-items, like documents or other nested categories.
    //         label: 'Introduction', // The label for this category in the sidebar. This is what will be displayed to the user.
    //         items: [
    //             {
    //                 type: 'doc', // Specifies that this item is a document link.
    //                 id: 'introduction/overview', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
    //                 label: 'Overview', // The label for the document in the sidebar. This is what will be displayed to the user.
    //             },
    //         ],
    //     },
    //     {
    //         type: 'category',
    //         label: 'Getting Started',
    //         items: [
    //             {
    //                 type: 'doc',
    //                 id: 'getting-started/installation',
    //                 label: 'Installation',
    //             },
    //             {
    //                 type: 'doc',
    //                 id: 'getting-started/setup-your-app',
    //                 label: 'Setup Your App',
    //             },
    //         ],
    //     },
    //     {
    //         type: 'category',
    //         label: 'Core Concepts',
    //         items: [
    //             {
    //                 type: 'category',
    //                 label: 'Annotations and Routing',
    //                 items: [
    //                     {
    //                         type: 'doc',
    //                         id: 'core-concepts/annotations-and-routing/using-controllers',
    //                         label: 'Using Controllers',
    //                     },
    //                     {
    //                         type: 'doc',
    //                         id: 'core-concepts/annotations-and-routing/defining-routes-with-annotations',
    //                         label: 'Defining Routes with Annotations',
    //                     },
    //                 ],
    //             },
    //             {
    //                 type: 'category',
    //                 label: 'Dependency Injection',
    //                 items: [
    //                     {
    //                         type: 'doc',
    //                         id: 'core-concepts/dependency-injection/registering-dependencies',
    //                         label: 'Registering Dependencies',
    //                     },
    //                     {
    //                         type: 'doc',
    //                         id: 'core-concepts/dependency-injection/configuring-dependencies',
    //                         label: 'Configuring Dependencies',
    //                     },
    //                 ],
    //             },
    //         ],
    //     },
    //     // {
    //     //     type: 'category',
    //     //     label: 'Handling Requests',
    //     //     items: [
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Request Parameters',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'handling-requests/request-parameters/accessing-body-query-path-headers',
    //     //                     label: 'Accessing Body, Query, Path, Headers',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Response Handling',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'handling-requests/response-handling/return-types-and-status-codes',
    //     //                     label: 'Return Types and Status Codes',
    //     //                 },
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'handling-requests/response-handling/custom-responses',
    //     //                     label: 'Custom Responses',
    //     //                 },
    //     //             ],
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'Advanced Features',
    //     //     items: [
    //     //         {
    //     //             type: 'category',
    //     //             label: 'WebSockets',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'advanced-features/websockets/using-built-in-websockets',
    //     //                     label: 'Using Built-in WebSockets',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Interceptors and Middleware',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'advanced-features/interceptors-and-middleware/creating-and-using-interceptors',
    //     //                     label: 'Creating and Using Interceptors',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Guards',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'advanced-features/guards/protecting-routes-with-guards',
    //     //                     label: 'Protecting Routes with Guards',
    //     //                 },
    //     //             ],
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'Lifecycle',
    //     //     items: [
    //     //         {
    //     //             type: 'doc',
    //     //             id: 'lifecycle/request-lifecycle',
    //     //             label: 'Request Lifecycle',
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'Error Handling',
    //     //     items: [
    //     //         {
    //     //             type: 'doc',
    //     //             id: 'error-handling/exception-filters',
    //     //             label: 'Creating and Using Exception Filters',
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'Examples and Tutorials',
    //     //     items: [
    //     //         {
    //     //             type: 'category',
    //     //             label: 'CRUD Operations',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'examples-and-tutorials/crud-operations/creating-reading-updating-deleting-endpoints',
    //     //                     label: 'Creating, Reading, Updating, Deleting Endpoints',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Real-time Features',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'examples-and-tutorials/real-time-features/implementing-websockets',
    //     //                     label: 'Implementing Websockets',
    //     //                 },
    //     //             ],
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'FAQ and Troubleshooting',
    //     //     items: [
    //     //         {
    //     //             type: 'category',
    //     //             label: 'FAQ',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'faq-and-troubleshooting/faq/common-questions-and-answers',
    //     //                     label: 'Common Questions and Answers',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Troubleshooting',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'faq-and-troubleshooting/troubleshooting/solving-common-issues',
    //     //                     label: 'Solving Common Issues',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Feedback and Roadmap',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'faq-and-troubleshooting/feedback-and-roadmap/reporting-issues',
    //     //                     label: 'Reporting Issues',
    //     //                 },
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'faq-and-troubleshooting/feedback-and-roadmap/feature-requests',
    //     //                     label: 'Feature Requests',
    //     //                 },
    //     //             ],
    //     //         },
    //     //     ],
    //     // },
    //     // {
    //     //     type: 'category',
    //     //     label: 'API Reference',
    //     //     items: [
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Annotations',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'api-reference/annotations/detailed-explanation-of-all-annotations',
    //     //                     label: 'Detailed Explanation of All Annotations',
    //     //                 },
    //     //             ],
    //     //         },
    //     //         {
    //     //             type: 'category',
    //     //             label: 'Classes and Methods',
    //     //             items: [
    //     //                 {
    //     //                     type: 'doc',
    //     //                     id: 'api-reference/classes-and-methods/detailed-reference-for-core-classes-and-methods',
    //     //                     label: 'Detailed Reference for Core Classes and Methods',
    //     //                 },
    //     //             ],
    //     //         },
    //     //     ],
    //     // },
    // ],
};

module.exports = sidebars;
