import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

    tutorialSidebar: [
        // Introduction
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'introduction', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Introduction', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Getting Started
        {
            type: 'category',
            label: 'Getting Started',
            items: [
                {
                    type: 'doc',
                    id: 'getting-started/installation',
                    label: 'Installation',
                },
                {
                    type: 'doc',
                    id: 'getting-started/create-your-first-endpoint',
                    label: 'Create Your First Endpoint',
                },
                {
                    type: 'doc',
                    id: 'getting-started/run-the-server',
                    label: 'Run the Server',
                },
            ],
        },
        // Core Concepts
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'core-concepts', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Core Concepts', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Handling Requests
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'handling-requests', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Handling Requests', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Advanced Features
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'advanced', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Advanced Features', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Lifecycle
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'lifecycle', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Lifecycle', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Error Handling
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'error-handling', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Error Handling', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // Examples and Tutorials
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'examples-and-tutorials', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'Examples and Tutorials', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // FAQ and Troubleshooting
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'faq-and-troubleshooting', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'FAQ and Troubleshooting', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
        // API Reference
        {
            type: 'doc', // Specifies that this item is a document link.
            id: 'api-reference', // The unique identifier (id) for this document. It's typically the file path (excluding the file extension) relative to the docs directory, such as docs/introduction/overview.md.
            label: 'API Reference', // The label for the document in the sidebar. This is what will be displayed to the user.
        },
    ],
};

module.exports = sidebars;
