name: revali_construct
description: Foundation for creating constructs for Revali
version: 1.7.0
repository: https://github.com/mrgnhnt96/revali/tree/main/packages/revali_construct
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
  - https://github.com/sponsors/mrgnhnt96
topics:
  - revali
  - api
  - backend
  - server
  - construct

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  analyzer: ^6.11.0
  equatable: ^2.0.5
  hotreloader: ^4.2.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ^1.15.0
  path: ^1.9.0
  revali_annotations: ^1.4.1
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  test: ^1.25.9
