name: zora
version: 0.0.1+1
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    analyzer: 6.4.1
    args: ^2.5.0
    code_builder: ^4.10.0
    collection: ^1.19.0
    dart_style: ^2.3.6
    equatable: ^2.0.5
    file: ^7.0.0
    json_annotation: ^4.9.0
    mason_logger: ^0.2.15
    path: ^1.9.0
    stack_trace: ^1.11.1
    stream_transform: ^2.1.0
    watcher: ^1.1.0
    yaml: ^3.1.2
    zora_annotations:
        path: ../zora_annotations
    zora_construct:
        path: ../zora_construct

dev_dependencies:
    build_runner: ^2.4.8
    json_serializable: ^6.8.0
    test: ^1.25.7

executables:
    zora:
