// THIS IS THE FILE THAT WILL BE GENERATED BY ZORA
// IN ORDER TO GENERATE THE CONSTRUCTS

import 'dart:io' as io;
import 'dart:isolate';

import 'package:zora_gen/zora_gen.dart';
import 'package:zora_shelf/zora_shelf.dart';

final constructs = <Construct>[
  ZoraShelfConstruct(),
];

const path = '/Users/morgan/Documents/develop.nosync/zora/examples/demo/routes';

void main(
  List<String> args, [
  SendPort? sendPort,
]) async {
  var result = await run(
    args,
    constructs: constructs,
    path: path,
  );
  sendPort?.send(result);
  io.exitCode = result;
}
