/// The entrypoint for the **client** environment.
///
/// Only the `@client` components are hydrated here — on this site that is the
/// ⌘K search dialog, plus `jaspr_content`'s own theme toggle and sidebar
/// button. Everything else is static HTML, which is the point of `mode: static`.
library;

import 'package:jaspr/client.dart';

// Generated by jaspr_builder from the @client annotations. Do not edit.
import 'main.client.options.dart';

void main() {
  Jaspr.initializeApp(options: defaultClientOptions);

  // [ClientApp] finds and hydrates every @client component the server rendered.
  runApp(const ClientApp());
}
