name: example_construct_app
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  revali_annotations:
    path: ../../../packages/revali_annotations
  revali_core:
    path: ../../../packages/revali_core

dev_dependencies:
  example_construct:
    path: ../
  example_construct_dup:
    path: ../../create_construct_dup
  revali:
    path: ../../../packages/revali
