name: zora_shelf
version: 0.0.1+1
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    shelf: ^1.4.1
    shelf_router: ^1.1.4
    zora_construct:
        path: ../zora_construct
