name: examples
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    zora_annotations:
        path: ../../packages/zora_annotations

dev_dependencies:
    mocktail: ^1.0.4
    zora:
        path: ../../packages/zora
    zora_shelf:
        path: ../../packages/zora_shelf
