name: examples
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    revali_annotations:
        path: ../../packages/revali_annotations
    revali_router:
        path: ../../packages/revali_router

dev_dependencies:
    mocktail: ^1.0.4
    revali:
        path: ../../packages/revali
    revali_shelf:
        path: ../../packages/revali_shelf
