name: examples
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    shelf: ^1.4.1
    shelf_router: ^1.1.4
    zora_core:
        path: ../../packages/zora_core

dev_dependencies:
    mocktail: ^1.0.4
    zora:
        path: ../../packages/zora
    zora_shelf:
        path: ../../packages/zora_shelf
