name: scripts
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    change_case: ^2.1.0
    file: ^7.0.1
    glob: ^2.1.2
    intl: ^0.20.0
    mason_logger: ^0.2.16
    path: ^1.9.1
    yaml: ^3.1.2
    yaml_edit: ^2.2.1
