name: revali_shelf
version: 0.0.1+1
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    code_builder: ^4.10.0
    dart_style: ^2.3.6
    shelf: ^1.4.1
    shelf_router: ^1.1.4
    revali_construct:
        path: ../revali_construct
