name: zora_construct
version: 0.0.1
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    equatable: ^2.0.5
    hotreloader: ^4.2.0
    json_annotation: ^4.9.0
    zora_annotations:
        path: ../zora_annotations

dev_dependencies:
    build_runner: ^2.4.11
    json_serializable: ^6.8.0
