name: test_suite
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - constructs/revali_server/methods
  - constructs/revali_server/return_types
  - constructs/revali_server/middleware
