name: test_suite
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

workspace:
  - constructs/revali_client/custom_return_types
  - constructs/revali_client/primitive_return_types
  - constructs/revali_client/methods
  - constructs/revali_client/websockets/return_types
  - constructs/revali_client/websockets/params
  - constructs/revali_server/methods
  - constructs/revali_server/custom_return_types
  - constructs/revali_server/primitive_return_types
  - constructs/revali_server/middleware
  - constructs/revali_server/params
