name: revali_router
version: 0.0.1+1
publish_to: 'none'

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    autoequal: ^0.9.1
    collection: ^1.19.0
    copy_with_extension: ^5.0.4
    equatable: ^2.0.5
    http_parser: ^4.1.0
    mime: ^1.0.5
    revali_router_core:
      path: ../revali_router_core

dev_dependencies:
    autoequal_gen: ^0.9.1
    build_runner: ^2.4.11
    copy_with_extension_gen: ^5.0.4
    mockito: ^5.4.4
    test: ^1.25.7
